plot-html:
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#FF4500","False":"#BA55D3"}' --format html --pacific-centered --markersize=15 --parameters=SkinAndBark --output=plots/SkinAndBark --missing-value="#808080" --with-layers
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#FF4500","False":"#BA55D3"}' --format html --pacific-centered --markersize=15 --parameters=TesticlesAndEgg --output=plots/TesticlesAndEgg --missing-value="#808080" --with-layers
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#FF4500","False":"#BA55D3"}' --format html --pacific-centered --markersize=15 --parameters=BoneAndRope --output=plots/BoneAndRope --missing-value="#808080" --with-layers
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#FF4500","False":"#BA55D3"}' --format html --pacific-centered --markersize=15 --parameters=EyeAndSeed --output=plots/EyeAndSeed --missing-value="#808080" --with-layers
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#FF4500","False":"#BA55D3"}' --format html --pacific-centered --markersize=15 --parameters=EyeAndFruit --output=plots/EyeAndFruit --missing-value="#808080" --with-layers
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#FF4500","False":"#BA55D3"}' --format html --pacific-centered --markersize=15 --parameters=MouthAndDoor --output=plots/MouthAndDoor --missing-value="#808080" --with-layers
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#FF4500","False":"#BA55D3"}' --format html --pacific-centered --markersize=15 --parameters=FootAndWheel --output=plots/FootAndWheel --missing-value="#808080" --with-layers

plot-jpg:
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=SkinAndBark --output=plots/SkinAndBark --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"},{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=EyeAndSeed,EyeAndFruit --output=plots/EyeAndSeed --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=TesticlesAndEgg --output=plots/TesticlesAndEgg --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=FingernailAndNailtool --output=plots/FingernailAndNailtool --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=HeadAndTop --output=plots/HeadAndTop --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"},{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"},{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=HeartAndFirewood,IntestinesAndBed,BellyAndPen --output=plots/HeartAndFirewood --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"},{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"},{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=ShoulderbladeAndSpade,ShoulderbladeAndOar,ShoulderbladeAndPaddle --output=plots/ShoulderbladeAndSpade --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"},{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"},{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=TendonAndRoot,BloodvesselAndRoot,VeinAndRoot --output=plots/TendonAndRoot --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=FootAndWheel --output=plots/FootAndWheel --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders
	cldfbench cldfviz.map cldf/cldf-metadata.json --colormaps '{"True":"#E66100","False":"#C3B1E1","None":"#DCDCDC"}' --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=160 --parameters=EarAndLeaf --output=plots/EarAndLeaf --zorder='{"True": 6, "False": 5, "None": 4}' --no-legend --no-borders

plot-family-map:
	cldfbench cldfviz.map cldf/cldf-metadata.json --language-properties-colormaps=tol --language-properties=Family --format jpg --width 20 --height 10 --dpi 300 --pacific-centered --markersize=110 --no-legend --no-borders --output=plots/family-map
	cldfbench cldfviz.map cldf/cldf-metadata.json --language-properties-colormaps=tol --language-properties=Family --format html --pacific-centered --markersize=15 --output=plots/family-map
